### ISSUE TITLE
老哥做的很棒，请问能不能提两个小功能

### ISSUE THREAD

**Issue by yyzfish** [wxtsky/MyWalletScan#1]
老哥做的很棒，提两个小功能，一个是usdc的余额显示，另外希望有个自动刷新

**Comment by wxtsky** [comment]
> 老哥做的很棒，提两个小功能，一个是usdc的余额显示，另外希望有个自动刷新

可以的，我这几天会更新上

**Comment by yyzfish** [comment]
感谢！
