### ISSUE TITLE
可以添加的功能

### ISSUE THREAD

**Issue by tiancong-netizen** [wxtsky/MyWalletScan#13]
1、计算各个链上GAS花费统计，以及交易记录
2、计算各个链有多少余额（usdt计算）
3、批量生产钱包，然后展示助记词、私钥、钱包地址

**Comment by wxtsky** [comment]
好的

**Comment by tiancong-netizen** [comment]
1、统计某个链上 这周、这个月、合计 三个维度花费的gas，同时查询这个链上当前的有多少余额（usdt计算）

**Comment by tiancong-netizen** [comment]
然后可以新增一个，和智能合约交互的次数，每个智能合约只统计一次
