### ISSUE TITLE
超过地址1000就报错，页面卡死

### ISSUE THREAD

**Issue by wkxtbb123** [wxtsky/MyWalletScan#15]
超过地址1000就报错，页面卡死

**Comment by wkxtbb123** [comment]
删除功能不可用

**Comment by wxtsky** [comment]
全部修复了

**Comment by wkxtbb123** [comment]
超过地址1000就报错，页面卡死
问题没有完全修复
1.导入地址太多，页面请求卡死（应该是先添加地址到网页中，在100一次请求获取资金记录）

**Comment by wkxtbb123** [comment]
![微信图片_20230520213324](https://github.com/wxtsky/MyWalletScan/assets/98833972/53988007-568c-426e-a190-86f40a0f8195)
请看我分享的图片

**Comment by leeggco** [comment]
1000 地址？

**Comment by wkxtbb123** [comment]
是的 卡死
