### ISSUE TITLE
有没有老哥有代码基础review一下，有无地址泄露风险

### ISSUE THREAD

**Issue by tufubaba** [wxtsky/MyWalletScan#16]

**Comment by luoyeETH** [comment]
地址存在localStorage里

**Comment by lhtuling** [comment]
以我浅薄知识查看并没有！而且单纯地址泄露有很大影响么？   小韭菜表示无所谓吧   也不是官方，官方的话可能还会做关联女巫什么的！我是下载下来源码自己在本地跑了！
