### ISSUE TITLE
本地请求starknet的url会报错，zk的是正常的

### ISSUE THREAD

**Issue by frankINdf** [wxtsky/MyWalletScan#19]
<img width="1079" alt="image" src="https://github.com/wxtsky/MyWalletScan/assets/20693600/d802ed9f-dca1-4d00-b30a-180dba56c0c7">

**Comment by frankINdf** [comment]
是你自己建了个graph数据库吗

**Comment by wxtsky** [comment]
不是啊  我这没问题的 你看下是不是梯子问题 你用的头盔钱包还是人字拖钱包

**Comment by frankINdf** [comment]
哦哦，好的，我再试下。这个starkscan.stellate.sh是个什么服务啊，我上网搜也没搜到，看starkscan的api也没这个

**Comment by frankINdf** [comment]
从chrome里copy了curl请求参数，转成js的解决了
