### ISSUE TITLE
还是有bug的

### ISSUE THREAD

**Issue by tiancong-netizen** [wxtsky/MyWalletScan#2]
1、无法修改备注 2、批量添加地址报异常，但是不影响正常操作， 3、最好是在批量导入的时候 地址+备注，这样就可以了

**Comment by wxtsky** [comment]
好的，修改备注的话是输入完按回车。别的问题我会修复。

**Comment by tiancong-netizen** [comment]
明白 能否加个V，一起探讨 web3撸毛事业 抱团取暖

**Comment by tiancong-netizen** [comment]
> 

stark l0 还有很多测试网络 这些后面会上查询吗
