### ISSUE TITLE
starkscan.stellate.sh是个什么服务

### ISSUE THREAD

**Issue by frankINdf** [wxtsky/MyWalletScan#20]
starkscan.stellate.sh是个什么服务啊，想要了解下，但是找不到相关资料，在starkscan也没看到

**Comment by wxtsky** [comment]
抓的包  stark的区块浏览器里有

**Comment by lhtuling** [comment]
![image](https://github.com/wxtsky/MyWalletScan/assets/44140500/a7c96a09-354f-4e92-9f07-d1d36ccedeab)

是的 抓包可以看到 https://starkscan.stellate.sh/

> starkscan.stellate.sh是个什么服务啊，想要了解下，但是找不到相关资料，在starkscan也没看到

**Comment by wxtsky** [comment]
只是个接口罢了

**Comment by lhtuling** [comment]
> 只是个接口罢了

是的大佬    可能是害怕你偷偷用自己接口获取他们啥东西吧  哈哈哈
不过我在想只有地址  能干啥呢。。。。好像没啥用哇    存起来看别人发财？

**Comment by wxtsky** [comment]
> > 只是个接口罢了
> 
> 
> 
> 是的大佬    可能是害怕你偷偷用自己接口获取他们啥东西吧  哈哈哈
> 
> 不过我在想只有地址  能干啥呢。。。。好像没啥用哇    存起来看别人发财？

是啊 做那种偷摸的事没意思的 为大家服务才有意思

**Comment by frankINdf** [comment]
没有这个意思啊，我也想研究下代码，以前也想过做类似的东西统计账户，但是没有找到接口，现在看到大佬这个项目，想学习下，谢谢啦
