### ISSUE TITLE
查询交易记录transactions接口由于数量限制报错

### ISSUE THREAD

**Issue by yangzhe1003** [wxtsky/MyWalletScan#24]
接口:https://zksync2-mainnet-explorer.zksync.io/transactions
参数:{
limit: 100
direction: older
accountAddress: 'xxxxxxxxxxxxxx'
fromBlockNumber: xxxxx
fromTxIndex: 4
offset: 500
}

接口400
返回结果:
(offset + limit) should not exceed 500

结果导致：页面某些参数Error
![企业微信截图_20230529143232](https://github.com/wxtsky/MyWalletScan/assets/32119554/954423d3-1fff-416d-bd0c-935849d45efe)

**Comment by wxtsky** [comment]
这个地址数据太多了
