### ISSUE TITLE
为什么本地运行的版本与您的在线版本不一样，少了Trustalabs分数。以及为什么要取消累积统计消耗gas和累积eth的部分？

### ISSUE THREAD

**Issue by hehe2046** [wxtsky/MyWalletScan#37]
为什么本地运行的版本与您的在线版本不一样，少了Trustalabs分数。以及为什么要取消累积统计消耗gas和累积eth的部分？

![image](https://github.com/wxtsky/MyWalletScan/assets/36158945/c1a48f47-296f-4958-bfc9-ebbbfae510e1)

![image](https://github.com/wxtsky/MyWalletScan/assets/36158945/82c3408c-d1fd-4529-bc19-ac0a1b49a65a)

**Comment by wxtsky** [comment]
> 为什么本地运行的版本与您的在线版本不一样，少了Trustalabs分数。以及为什么要取消累积统计消耗gas和累积eth的部分？
> 
> 
> 
> ![image](https://github.com/wxtsky/MyWalletScan/assets/36158945/c1a48f47-296f-4958-bfc9-ebbbfae510e1)
> 
> 
> 
> ![image](https://github.com/wxtsky/MyWalletScan/assets/36158945/82c3408c-d1fd-4529-bc19-ac0a1b49a65a)
> 
> 
> 
> 

我还没上传到github  还有几个bug待修复  这两天就上传了
