### ISSUE TITLE
构建后的文件 打开 404

### ISSUE THREAD

**Issue by pacemankun** [wxtsky/MyWalletScan#5]
![image](https://user-images.githubusercontent.com/26589212/236421329-d9065dd6-5498-42dc-b4ee-ea7b156882b8.png)
<img width="401" alt="image" src="https://user-images.githubusercontent.com/26589212/236421576-2a7eef99-7a76-4244-98bd-f7edc4cc9d68.png">
求助 怎么搞

**Comment by wxtsky** [comment]
html里面 那个路径 前面加个  .  试试

**Comment by pacemankun** [comment]
老哥 你构建出来的html 打开没问题吗？我这卡主了

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/26589212/236425613-b9d41ae1-0ba1-4111-ad13-120d8d569fab.png">

**Comment by wxtsky** [comment]
加一个点就行 不是两个点

**Comment by pacemankun** [comment]
你说的对，同级目录   
然而 还是不行 
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/26589212/236442332-85157da7-a722-4535-b547-8d55e996c848.png">
老哥，你打包一下 能帮我截个图吗 我对比一下

**Comment by wxtsky** [comment]
![image](https://user-images.githubusercontent.com/79189721/236443209-387407bf-d133-41c8-abec-2dd65944a59e.png)


你直接双击打开index.html试试

**Comment by pacemankun** [comment]
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/26589212/236444202-4ffa9476-89e0-4f3c-bf4b-7eb814546798.png">
貌似不支持file 协议
你可以直接本地打开这个html 不报错吗？

**Comment by pacemankun** [comment]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/26589212/236444597-398c3016-e4b0-4df7-b059-64b78265d233.png">
