### ISSUE TITLE
L0 Tx准确率问题 

### ISSUE THREAD

**Issue by fomsun** [wxtsky/MyWalletScan#6]
L0Tx会少一个 后面看代码发现大佬是使用方法ID来实现的 

发现缺少 0xc858f5f9 这个方法 他的Tx也是属于L0

可以在这个平台校验结果
https://dune.com/queries/2300794/3768773

这是完整的L0 TX方法ID

const methodIds = [
    "0x9fbf10fc", "0x1114cd2a", "0x76a9099a", "0x2e15238c", "0xae30f6ee", "0xc45dec27", "0x2cdf0b95", "0x879762e2",
    "0x656f3d64", "0x51905636", "0xad660825", "0xfe359a0d", "0xca23bb4c", "0xc858f5f9"
];

**Comment by wxtsky** [comment]
谢谢谢谢 太感谢了！

**Comment by fomsun** [comment]
可以加个wx交流吗 我这边按照你的思路也开发了一套 Base64：c2xtMjIwNQ==
